apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: prevent-deletion-in-protected-namespaces
spec:
  validationFailureAction: Enforce  # Change to "Audit" to test before enforcing
  background: false
  rules:
  - name: block-resource-deletion
    match:
      resources:
        kinds:
        - "*"
        namespaces:
        - ingress-nginx
        - cert-manager
        - external-dns
    preconditions:
      all:
      - key: "{{ request.operation }}"
        operator: Equals
        value: "DELETE"
    validate:
      message: "Deleting resources in protected namespaces is not allowed."
      deny: {}
