name: Cleanup

on: workflow_dispatch

permissions:
  id-token: write       # Required for OIDC
  contents: read        # To read repo content

jobs:
  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::255945442255:role/github-actions-eks-demo-role
          aws-region: ap-southeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform-learner-cluster

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./terraform-learner-cluster