name: Terraform EKS Deployment

on:
  workflow_dispatch:
    inputs:
      region:
        description: "AWS region"
        required: true
        default: "ap-southeast-1"

permissions:
  id-token: write       # Required for OIDC
  contents: read        # To read repo content

jobs:
  deploy:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::255945442255:role/github-actions-eks-demo-role
          aws-region: ${{ inputs.region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform-learner-cluster

      - name: Terraform Plan
        working-directory: ./terraform-learner-cluster
        env:
          TF_VAR_region: ${{ inputs.region }}
        run: terraform plan
        
      - name: Terraform Apply
        working-directory: ./terraform-learner-cluster
        env:
          TF_VAR_region: ${{ inputs.region }}
        run: terraform apply -auto-approve
