name: Terraform EKS Deployment

on: 
  workflow_dispatch:
    inputs:
      enable_external_dns:
        description: "Enable ExternalDNS"
        type: choice
        options:
          - "true"
          - "false"
        default: "true"
        required: false

      enable_loki_s3:
        description: "Enable Loki S3"
        type: choice
        options:
          - "true"
          - "false"
        default: "true"
        required: false

      enable_ebs_csi_driver_role:
        description: "Enable EBS CSI Driver Role"
        type: choice
        options:
          - "true"
          - "false"
        default: "true"
        required: false

permissions:
  id-token: write       # Required for OIDC
  contents: read        # To read repo content

jobs:
  deploy:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::255945442255:role/github-actions-eks-demo-role
          aws-region: ap-southeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform-learner-cluster

      - name: Terraform Plan
        working-directory: ./terraform-learner-cluster
        env:
          TF_VAR_enable_external_dns: ${{ inputs.enable_external_dns }}
          TF_VAR_enable_loki_s3: ${{ inputs.enable_loki_s3 }}
          TF_VAR_enable_ebs_csi_driver_role: ${{ inputs.enable_ebs_csi_driver_role }}
        run: terraform plan
        
      - name: Terraform Apply
        working-directory: ./terraform-learner-cluster
        env:
          TF_VAR_enable_external_dns: ${{ inputs.enable_external_dns }}
          TF_VAR_enable_loki_s3: ${{ inputs.enable_loki_s3 }}
          TF_VAR_enable_ebs_csi_driver_role: ${{ inputs.enable_ebs_csi_driver_role }}
        run: terraform apply -auto-approve
